### PR TITLE
Release 1.1.2

### PR DESCRIPTION
**Pull request by machacekondra**
Change-Id: I1daa5dbe90fe00754282db7f4d3efb06ff1638a4
Signed-off-by: Ondra Machacek <omachace@redhat.com>

### CODE REVIEW

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Comment by ifireball** [comment]
@machacekondra is something wrong with the ci build?

**Comment by machacekondra** [comment]
> @machacekondra is something wrong with the ci build?

Nope it's working.

**Pull request merged**
